### ISSUE TITLE
Wrong layout in 1.0.7 when input is short

### ISSUE THREAD

**Issue by xak2000** [ruhley/angular-color-picker#70]
Afger upgrading to 1.0.7 the layout is broken if input width is small.

https://plnkr.co/edit/vqmYT5wKXVcQMkeG8D0T?p=preview (Make preview viewport wider then 768 px to display `form-inline` properly).

Also the vertical align is broken too. Try to comment `vertical-align: middle;` in custom `.color-picker-wrapper` css. This is broken after 1.0 actually (when bootstrap removed), but this can be easily workaround. But layout bug introduced in 1.0.7 is not so easy.

I tried this plunkr with CSS from version 1.0.6 and layout is fine.

**Comment by xak2000** [comment]
I think PR #68 is bad. Using relative positioning is wrong here.

**Comment by ruhley** [comment]
If I change the css in the plunker to 

```css
.issue-label-form .color-picker-input-wrapper {
  display: inline-block;
  vertical-align: middle;
  width: auto;
}
```

then it works fine for me.

**Comment by xak2000** [comment]
It doesn't work for me with `width: auto` set on any `color-picker-wrapper` or `color-picker-input-wrapper` element.

In first case the field width is ok, but the color chooser layout is broken.
In second case the color chooser layout is ok, but it's input field is on wrong row. All input-field parents should be `inline-block` or else it will be on next row.

This is `form-inline` - all fields should be in one row (if the viewport width is more then 768px).
With `width: auto;` the colorpicker's input element collapses to minimal possible width (and it is intended and wanted behaviour), but color chooser div also triyng to be minimal possible width. And it is wrong behaviour.

If you really think something wrong with previous absolute positioning, I think we can leave relative positioning but make another container for color-picker-panel:

```
.color-picker-panel-wrapper {
  width: 192px; // max if tansparency selector is enabled
  background: transparent;
  pointer-events: none;
}
```

`.color-picker-panel` will be inside it and all elements inside `.color-picker-panel` will have relative position.

I think this should work.

**Comment by xak2000** [comment]
I updated original [plunkr](https://plnkr.co/edit/vqmYT5wKXVcQMkeG8D0T?p=preview) to better show the problem.

**Comment by michal-szepielak** [comment]
Hi,

I made pull request with the fix of this issue: https://github.com/ruhley/angular-color-picker/pull/72

**Comment by xak2000** [comment]
@michal-szepielak Your pull request not fixes this issue at all. This issue does not use `swatchOnly` option.

**Comment by xak2000** [comment]
Another [solution](https://plnkr.co/edit/XCf5UqaCpHfpqCSZDRZB?p=preview):

```
.color-picker-wrapper .color-picker-panel {
  display: table-row;
}
.color-picker-wrapper .color-picker-panel .color-picker-grid {
  display: table-cell;
  float: initial; /* remove float: left; */
}
.color-picker-wrapper .color-picker-panel .color-picker-hue,
.color-picker-wrapper .color-picker-panel .color-picker-opacity {
  display: table-cell;
  padding-left: 20px;
  border-left: 1px solid white;
  float: initial; /* remove float: left; */
  width: initial; /* remove width: 20px; */
  margin-left: initial; /* remove margin-left: 1px; */
}
```

**Comment by xak2000** [comment]
@ruhley I can make a PR if you want.

**Comment by ruhley** [comment]
@xak2000 @michal-szepielak @paulking00 I have pushed a fix to master using `display: table-cell;`. Would you all be able to do a quick test before I create a release. My tests all look good.

**Comment by paulking00** [comment]
Yes, the CSS in master on github works great for me!

(master in bower is at a completely different stage!)

Cheers :-)

**Comment by xak2000** [comment]
@ruhley It works but with small bugs on page zoom.

Set page zoom in Chrome to 125% (press <kbd>Ctrl</kbd> + <kbd>Num+</kbd> twice).
You will see strange 2px gap between `.color-picker-grid` and `.color-picker-hue` elements. It should be 1px.
Also there is no gap between `.color-picker-hue` and right gray border. It should be gap of 1px white.

I think there is something with `left: 1px;` or so. In any case my variant (see css from my previous post) is working fine even when brower zoom is set to 125%.

Rendering on zoom 125% from master branch:
![](http://i.imgur.com/P4pY7ja.png)

Rendering on zoom 125% with css from my previous post:
![](http://i.imgur.com/X5hWzJ9.png)

**Comment by michal-szepielak** [comment]
@ruhley it doesn't work for me in Mac Firefox. 
![image](https://cloud.githubusercontent.com/assets/6048241/15014931/1287dd1a-1233-11e6-8d38-cd499508b50d.png)

This issue persists also in @xak2000's Plunker

**Comment by xak2000** [comment]
@michal-szepielak I just reproduced this in Firefox on Ubuntu. Very strange... `table-cell` causes it.

**Comment by xak2000** [comment]
I fixed it removing `height: 150px;` from `.color-picker-hue` and `.color-picker-opacity` classes.
But it still is very strange.. Can anybody [test it](https://plnkr.co/edit/BtZGir8SvAvzmcmLBeXA?p=preview) in other browsers? I have only Chrome and FF.

**Comment by michal-szepielak** [comment]
In FF, Chrome & Safari (on OS X) looks good besides 1 minor issue:
![image](https://cloud.githubusercontent.com/assets/6048241/15019510/8e65603c-1248-11e6-8bb3-0bff700dbbba.png)

**Comment by xak2000** [comment]
It can be fixed by adding `z-index: 10;` to `.color-picker-picker` class.

**Comment by ruhley** [comment]
@xak2000 @michal-szepielak @paulking00 I have pushed another fix to master hopefully fixing all your problems.

@xak2000 I have added css in the boostrap theme file to handle `.form-inline` now, so you shouldn't need your custom css for that any more.

I have updated the plunker at https://plnkr.co/edit/0oeSkBRp4LxgeHmKl3aF?p=preview

**Comment by xak2000** [comment]
@ruhley Thanks, it works now. Tested it in latest Chrome and Firefox on Win7.

But then I tried it in Firefox 24 ESR and it's broken:
![](http://i.imgur.com/DsSS6hH.png)
(color-picker-slider on wrong position, no gap between color-picker-grid and color-picker-hue)

And in IE11:
![](http://i.imgur.com/bTKl1Ef.png)
(color-picker-slider doesn't move with mouse)

Not sure whether you need to support these browsers (I don't need), but I tested 1.0.6 in them and all works fine! So maybe 1.0.6 layout is still better for cross-browser compatability... And we need to use it and just fix this border bug when opacity selector is on, and not introduce this table layout etc.

**Comment by michal-szepielak** [comment]
@ruhley picker on Safari, FF and Chrome on Mac works good.

There is one small detail. The cursor (crosshair) is not in the center of circle when picking some color. It's about 1px on the left from center

**Comment by ruhley** [comment]
@xak2000 I don't mind about Firefox 24. I have fixed the IE bug.

@michal-szepielak I will create a separate bug for the crosshair being in the wrong position. I seems to be happening on all browsers. I want to release these fixes as it is a major bug.

**Comment by ruhley** [comment]
Released [v1.1.0](https://github.com/ruhley/angular-color-picker/releases/tag/v1.1.0) with a new inline feature. Please reopen if the issue persists.
